package autocode

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	DeviceApi
	TestcaseApi
	ReportApi
	TestsetApi
	TestRunnerApi
	DeviceConsoleApi
	JobApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
