package autocode

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	DeviceRouter
	TestcaseRouter
	TestsetRouter
	TestRunnerRouter
	DeviceConsoleRouter
	JobRouter
	ReportRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
